//
export const CHECK_USER_ID_REQUEST = "USER/CHECK_USER_ID_REQUEST";
export const CHECK_USER_ID_SUCCESS = "USER/CHECK_USER_ID_SUCCESS";
export const CHECK_USER_ID_FAILURE = "USER/CHECK_USER_ID_FAILURE";

export const LOGIN_REQUEST = "USER/LOGIN_REQUEST";
export const LOGIN_SUCCESS = "USER/LOGIN_SUCCESS";
export const LOGIN_FAILURE = "USER/LOGIN_FAILURE";
